project:
  type: book
  # change output-dir to "docs" to publish to gh pages
  output-dir: docs

book:
  title: "MN Peatland Carbon Modeling"
  author: "K. O'Connor, N. Jelinski and the Lowland Conifer Team"
  date: "June 24, 2026"
  cover-image: "aksdb-badge-02.png"
  
  chapters:
    - index.md
    - x01-point-data-curation.md
    - x02-covariate-curation.md
	# add a chapter on X
    - x03-model-implementation.md
    - x04-results.md
    - x05-discussion.md
    - new-thing.md
  appendices:
    - references.md

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual


