project:
  type: book
  # change output-dir to "docs" to publish to gh pages
  output-dir: docs

book:
  title: "MN Peatland Carbon Modeling"
  author: "K. O'Connor, N. Jelinski and the Lowland Conifer Team"
  date: "June 24, 2026"
  cover-image: "aksdb-badge-02.png"
  
  chapters:
    - index.qmd
    - x01-point-data-curation.qmd
    - x02-covariate-curation.qmd
	# add a chapter on X
    - x03-model-implementation.qmd
    - x04-results.qmd
    - x05-discussion.qmd
    - new-thing.qmd
  appendices:
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual


